---
title: "Kepemimpinan dan Kekuasaan dalam Agribisnis"
description: |
  Pengantar terhadap kepemimpinan dan kekuasaan.
author: 
  - name: Tedy Herlambang
    url: https://bangtedy.github.io
    orcid_id: 0000-0002-7296-4357
date: 2022-03-09
draft: false
base_url: https://bangtedy.github.io/pimagribisnis
twitter:
  creator: "@t_hlb"
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Pendahuluan

* Pasokan pangan yang cukup kuantitas dan kualitasnya sangat penting bagi keberlangsungan kehidupan manusia. 
* Sejarah menunjukkan sebuah peradaban dapat runtuh jika sistem pasokan pangannya goyah. 
* Untuk membangun sistem pangan yang kokoh dibutuhkan kepemimpinan yang efektif.
* Disaat kekeringan, banjir, gunung meletus, perang, pandemi, depresi ekonomi: apa yang dicari rakyat --> peran kepemimpinan?
* Dengan menerapkan iptek dan kepemimpinan visioner, manusia berhasil menghasilkan pasokan pangan yang cukup.
* Tetapi disisi lain masih terdapat persoalan mekanisme distribusi pangan.


### Mengapa diperlukan kepemimpinan di Pertanian?

* Beberapa fokus pada aspek teknis: produksi, pengolahan, keuangan, distribusi dll.
* Beberapa orang yang bagus kemampuan teknisnya, diangkat ke posisi jabatan lebih tinggi.
* Kepemimpinan lebih dari manajemen
* Manajemen salah satu alat di dalam kepemimpinan



### Mengapa sangat diperlukan kepemimpinan di Pertanian?

* Semakin kompleks: melibatkan ilmu-ilmu sains, teknik dan ekonomi
* Peningkatan kebutuhan kepemimpinan agar aspek-aspek itu berjalan harmonis. 



### Definisi Kepemimpinan

* Proses mempengaruhi orang lain yang diarahkan untuk membentuk perilakunya 
* Pertanyaan: taktik apa yang bisa dipakai untuk mencoba mempengaruhi orang lain?
* Teman Anda mencoba mempengaruhi Anda agar mau makan di warung yang Anda tidak suka


### Kepemimpinan vs Manajemen
Apa perbedaan antara leadership dengan management?


### Tantangan Kepemimpinan

* Tantangan kepemimpinan agribisnis di jaman *Now*

### Kekuasaaan dan Kepemimpinan

* Jenis-jenis kekuasaan
* Penggunaan, keterbatasan dan dampak pemakaian kekuasaan
